Fix login presenter
birdy-messenger/Android-client pull request #17
Opened 2019-07-09 17:35 UTC by Aroize

2019-07-09 20:01 UTC, AntipovAndrey requested changes
Потом, после этих исправлений надо сделать использование валидатора в презентере. Сейчас пока так можно оставить.
После аппрува и мержа надо сделать пр в мастер

2019-07-09 20:01 UTC, AntipovAndrey commented on app/src/main/java/com/birdyteam/birdyandroidversion/data/network/api/app/input/Info.kt
> +data class Info (val id : Int, val token : Long)
Пробел лишний
Во всех файлах сделай автоформатировние (можно на корневом пакете нажать ctrl alt l)

2019-07-09 20:01 UTC, AntipovAndrey commented on app/src/main/java/com/birdyteam/birdyandroidversion/data/network/api/app/input/Info.kt
> +data class Info (val id : Int, val token : Long)
Название класса не очень
Что за инфо ты сохраняешь? Надо конкретнее назвать

2019-07-09 20:01 UTC, AntipovAndrey commented on app/src/main/java/com/birdyteam/birdyandroidversion/data/repository/UserAuthInfoRepository.kt
> +package com.birdyteam.birdyandroidversion.data.repository
Интерфейс репозитория лежит в domain
Т.к. уровень логики говорит (через интерфейс) как он хочет работать с данными. Реализация, обслуживая уровень логики, лежит в data.
domain - центральный слой при таком разбиении, presentation и data зависят от него, а не наоборот
зависят значит, что во-первых в domain нет импортов из data\presentation, во-вторых, в идеале, не domain подстраивается под data, а наоборот

2019-07-09 20:01 UTC, AntipovAndrey commented on app/src/main/java/com/birdyteam/birdyandroidversion/data/network/api/app/input/Info.kt
> +package com.birdyteam.birdyandroidversion.data.network.api.app.input
```Info``` это сущность, которую создает Интерактор, чтобы передать в Репозиторий
Эта модель должна лежать в domain.
И непонятно почему вообще она лежит в ```data.network.api.app.input```, она же вроде по сети не передается

2019-07-09 20:01 UTC, AntipovAndrey commented on app/src/main/java/com/birdyteam/birdyandroidversion/domain/interactor/SignInInteractor.kt
> +) {
Про стиль: добавляй пробел после объявления класса
```kotlin
class Interactor(
...
) {

    fun foo() {
    }
}
```

2019-07-09 20:01 UTC, AntipovAndrey commented on app/src/main/java/com/birdyteam/birdyandroidversion/user/CurrentUser.kt
> +object CurrentUser {
Пора избавляться уже от этого класса

2019-07-09 20:01 UTC, AntipovAndrey commented on app/src/main/java/com/birdyteam/birdyandroidversion/domain/repository/UserAuthInfoRepositoryImpl.kt
> +class UserAuthInfoRepositoryImpl(private val sharedPreferences: SharedPreferences) : UserAuthInfoRepository {
Лучше принимай контекст, и уже от него создавай себе sharedPreferences

2019-07-09 20:01 UTC, AntipovAndrey commented on app/src/main/java/com/birdyteam/birdyandroidversion/domain/validation/ValidateLoginInput.kt
> +                in 0..5 -> {
Синтаксически тут не нужно в фигурные скобки
можно просто 
```kotlin
return when(input.password.length) {
    in 0..5 -> ValidationResult.TOO_SHORT_PASSWORD
    else -> ValidationResult.TOO_LONG_PASSWORD
}

2019-07-09 20:01 UTC, AntipovAndrey commented on app/src/main/java/com/birdyteam/birdyandroidversion/domain/validation/ValidateLoginInput.kt
> +                in 0..5 -> {
```5``` лучше брать из ```InputPatterns```
Вдруг там сменят с 6 на 8, и тебе придется помнить, что надо 5 на 7 менять еще и тут

2019-07-09 20:01 UTC, AntipovAndrey commented on app/src/main/java/com/birdyteam/birdyandroidversion/domain/validation/ValidateLoginInput.kt
> +    fun validate(input: LoginInput): ValidationResult {
Надо как-то возвращать результат валидаци для всех полей. Иначе будет такая ситуация
Пусть и email и пароль невалидны
Нажимаешь Логин, возвращается ```ValidationResult.EMAIL_NOT_MATCH```, ты пишешь над полем (или в диалоге) - Неправильный формат почты. Пользователь исправляет почту, оставляя тот пароль. И при нажатии Логин он получает, что еще и пароль кривой. 
Хорошо, что бы приходил результат валидации всех полей. Можно сделат еще один data class под это дело, который будет хранить два енама - результат для email и пароля.
Причем енамы будут разные - один для результатов email, второй для password

2019-07-09 20:01 UTC, AntipovAndrey commented on app/src/main/java/com/birdyteam/birdyandroidversion/domain/validation/ValidateLoginInput.kt
> +        if(!input.password.matches(Regex(InputPatterns.PASSWORD_PATTERN))) {
Думаю не нужно тут такое регулярное выражение. Проще будет сделать 3 ветки when - когда пароль слишком короткий, слишком длинный, или когда он нормальный

2019-07-09 20:01 UTC, AntipovAndrey commented on app/src/main/java/com/birdyteam/birdyandroidversion/presentation/auth/signin/presenter/LoginPresenter.kt
> +        if (hasSharedPreferences()) {
Эта проверка странная
Ты тут проверяешь нужно ли тебе вообще делать логин.
Этон надо делать на предыдущем экране, на ui скрывать\отображать кнопку входа в зависимости от того вошел ли юзер или нет.
Так ты логику необходимости логика вставил в сам экран логина.

2019-07-09 20:01 UTC, AntipovAndrey commented on app/src/main/java/com/birdyteam/birdyandroidversion/presentation/auth/signin/presenter/LoginPresenter.kt
>                  .subscribeOn(Schedulers.newThread())
Уже не нужно - переключение наверху есть уже

2019-07-09 20:01 UTC, AntipovAndrey commented on app/src/main/java/com/birdyteam/birdyandroidversion/presentation/auth/signin/presenter/LoginPresenter.kt
>                      CurrentUser.id = it.id
Это не нужно уже - все в интеракторе сохранилось

2019-07-11 16:26 UTC, Aroize commented on app/src/main/java/com/birdyteam/birdyandroidversion/presentation/auth/signin/presenter/LoginPresenter.kt
> +        if (hasSharedPreferences()) {
У меня LoginActivity - стоит как Launch - activity. Этой проверкой я хотел сделать задел на будущее - что мол если в памяти сохранены и токен и id - надо перейти на экран приложения. 
(при этом текущий экран LoginActivity помечен как noHistory=true, то есть при кнопке back откинет из приложения, а не опять на логин. Оставлять проверку на ui мне кажется довольно странным. Я думаю вынести чуть позже это дело в репозиторий даты (а impl в domain)

2019-07-11 20:56 UTC, closed without merging